[theme]
base="dark"
primaryColor="#2e379c"

[[pages]]
path = "app.py"
icon = "ğŸ”"
name = "Explore"

[[pages]]
name = "Articles and Blogs"
icon = "ğŸ“"
is_section = true

[[pages]]
path = "pages/article_generator.py"
name = "Article Generator"


[[pages]]
path = "pages/blog_title_generator.py"
name = "Blog Title Generator"


[[pages]]
name = "Ads and Marketing"
icon = "ğŸ“ˆ"
is_section = true

[[pages]]
path = "pages/ad_headline_generator.py"
name = "Ad Headline Generator"

[[pages]]
name = "Social Media"
icon = "ğŸ“±"
is_section = true

[[pages]]
path = "pages/post_caption_generator.py"
name = "Post Caption Generator"

[[pages]]
path = "pages/content_plan_generator.py"
name = "Content Plan Generator"

[[pages]]
name = "E-Commerce"
icon = "ğŸ›’"
is_section = true

[[pages]]
path = "pages/product_description_generator.py"
name = "Product Description Generator"

[[pages]]
path = "pages/product_listing_generator.py"
name = "Product Listing Generator"