[theme]
base="dark"
primaryColor="#2e379c"

[[pages]]
path = "app.py"
name = "Explore"

[[pages]]
name = "Articles and Blogs"
icon = "ğŸ“"
is_section = true

[[pages]]
path = "pages/article_generator.py"
name = "Article Generator"


[[pages]]
path = "pages/blog_title_generator.py"
name = "Blog Title Generator"


[[pages]]
name = "Ads and Marketing"
icon = "ğŸ“ˆ"
is_section = true

[[pages]]
name = "Social Media"
icon = "ğŸ“±"
is_section = true

[[pages]]
name = "E-Commerce"
icon = "ğŸ›’"
is_section = true
